# Generated by Django 4.2.18 on 2025-01-15 09:07

from django.db import migrations, models


def add_initial_quotes(apps, schema_editor):
    Quotes = apps.get_model('quotes', 'Quotes')
    Quotes.objects.bulk_create([
        Quotes(text="Love your time registration."),
        Quotes(text="Intelligent time registration."),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                (
                    'id', models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(add_initial_quotes),
    ]
