name: deploy

on:
  workflow_dispatch:
    # push:
    #   branches:
    #     - solution

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: | 
          docker build -t quotes-app:latest .

      - name: "Tag Docker Images"
        run: |
         docker tag quotes-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/quotes-app:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Push to Docker Hub"
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/quotes-app:latest

      - name: Add SSH private key
        run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa

      - name: Add SSH known hosts 
        run: |
         ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
         echo "${{ secrets.DOT_ENV }}" > .env

      - name: Deploy to Dev server
        
        run: | 
          # split the IP  at the , and store them into var: IPs.
          IPs=(${secrets.IP//,/ })

          # Transfer .env file to SSH_HOST_1
          scp -o StrictHostKeyChecking=no .env ubuntu@${IPs[0]}:/home/ubuntu/.env
          
          #the shell script below loops over the number of IP adresses provided in the secrets.SSH_HOST and deploys the applicaiton
          ssh -o StrictHostKeyChecking=no ubuntu@${IPs[0]} << 'EOF'
          sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/quotes-app:latest
          sudo docker stop quotes-app || true
          sudo docker rm quotes-app || true
          sudo docker run --env-file /home/ubuntu/.env -d --name quotes-app -p 8000:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/quotes-app:latest
          EOF

          # Transfer .env file to SSH_HOST_2
          scp -o StrictHostKeyChecking=no .env ubuntu@${IPs[1]}:/home/ubuntu/.env

          ssh -o StrictHostKeyChecking=no ubuntu@${IPs[1]} << 'EOF'
          sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/quotes-app:latest
          sudo docker stop quotes-app || true
          sudo docker rm quotes-app || true          
          sudo docker run --env-file /home/ubuntu/.env -d --name quotes-app -p 8000:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/quotes-app:latest
          EOF

          
